#!/bin/sh

# usage:
#
# ocl2html commands/extended.ocl help
#
# this will create a help.html file from the ./commands/extended.ocl comments

src=$1
dest=$2
# grep '^\# ' $doc
# filename=${1%.*}
# filename=$filename".txt"
filename=$dest".adoc"

# print all but the first column
grep '^#' $src | sed 's/^# //' > $filename
# remove spacing lines
sed 's/^#$//' -i $filename
sed 's/^#*//' -i $filename
# cat $filename
# convert to html
asciidoctor $filename
