#!/bin/sh

# # v0.0.0
# # usage:
# #
# # ocl2html commands/extended.ocl help
# #
# # this will create a help.html file from the ./commands/extended.ocl comments

# src=$1
# dest=$2
# # grep '^\# ' $doc
# dest="${src%.*}"
# # filename=$filename".txt"
# filename=$dest".adoc"
# echo $src
# echo $dest
# echo $filename

# # print all but the first column
# grep '^#' $src | sed 's/^# //' > $filename
# # remove spacing lines
# sed 's/^#$//' -i $filename
# sed 's/^#*//' -i $filename
# # convert to html
# asciidoctor $filename
