#!/bin/sh

src=$1
dest=$2
# grep '^\# ' $doc
# filename=${1%.*}
# filename=$filename".txt"
filename=$dest".txt"

# print all but the first column
grep '^#' $src | sed 's/^# //' > $filename
# remove spacing lines
sed 's/^#$//' -i $filename
sed 's/^#*//' -i $filename
# cat $filename
# convert to html
asciidoctor $filename
